%% h = r2starGUI_handle_panel_dataIO(hParent,hFig,h,position)
%
% Input
% --------------
% hParent       : parent handle of this panel
% hFig          : handle of the GUI
% h             : global structure contains all handles
% position      : position of this panel
%
% Output
% --------------
% h             : global structure contains all new and other handles
%
% Description: This GUI function creates a panel for I/O control
%
% Kwok-shing Chan @ DCCN
% k.chan@donders.ru.nl
% Date created: 21 April 2018
% Date last modified: 22 April 2018
%
%
function h = r2starGUI_handle_panel_dataIO(hParent,hFig,h,position)

h.StepsPanel.dataIO = uipanel(hParent,'Title','I/O',...
    'Position',[position(1) position(2) 0.95 0.2],...
    'backgroundcolor',get(hFig,'color'));
    % input
    h.dataIO.text.input = uicontrol(h.StepsPanel.dataIO,'Style','text','String','mGRE image:',...
        'Units','normalized','Position', [0.01 0.8 0.2 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Input directory contains NIfTI file');
    h.dataIO.edit.input = uicontrol('Parent',h.StepsPanel.dataIO,'Style','edit',...
        'units','normalized','position',[0.21 0.8 0.68 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.input = uicontrol('Parent',h.StepsPanel.dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.8 0.1 0.15],...
        'backgroundcolor','white');
    % output
    h.dataIO.text.output = uicontrol('Parent',h.StepsPanel.dataIO,'Style','text','String','Output dir:',...
        'units','normalized','Position',[0.01 0.64 0.2 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Output directory');
    h.dataIO.edit.output = uicontrol('Parent',h.StepsPanel.dataIO,'Style','edit',...
        'units','normalized','position',[0.21 0.64 0.68 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.output = uicontrol('Parent',h.StepsPanel.dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.64 0.1 0.15],...
        'backgroundcolor','white');
    % mask files
    h.dataIO.text.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,'Style','text','String','Brain mask file:',...
        'units','normalized','Position',[0.01 0.48 0.2 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Specify mask file (NIfTI format). If the input directory contains NIfTI file with *mask* in the file name then it will be read automatically.');
    h.dataIO.edit.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,'Style','edit',...
        'units','normalized','position',[0.21 0.48 0.68 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.maskdir = uicontrol('Parent',h.StepsPanel.dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.48 0.1 0.15],...
        'backgroundcolor','white');
    % TE file
    h.dataIO.text.teFile = uicontrol('Parent',h.StepsPanel.dataIO,'Style','text','String','TE file',...
        'units','normalized','Position',[0.01 0.32 0.2 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Use FSL brain extraction (bet)');
    h.dataIO.edit.teFile = uicontrol('Parent',h.StepsPanel.dataIO,'Style','edit',...
        'units','normalized','position',[0.21 0.32 0.68 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white');
    h.dataIO.button.teFile = uicontrol('Parent',h.StepsPanel.dataIO,'Style','pushbutton','String','open',...
        'units','normalized','position',[0.89 0.32 0.1 0.15],...
        'backgroundcolor','white');
    % user TE input
    h.dataIO.text.userTE = uicontrol('Parent',h.StepsPanel.dataIO,'Style','text','String','or user input TEs:',...
        'units','normalized','Position',[0.01 0.16 0.2 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor',get(hFig,'color'),...
        'tooltip','Specify mask file (NIfTI format). If the input directory contains NIfTI file with *mask* in the file name then it will be read automatically.');
    h.dataIO.edit.userTE = uicontrol('Parent',h.StepsPanel.dataIO,'Style','edit',...
        'units','normalized','position',[0.21 0.16 0.78 0.15],...
        'HorizontalAlignment','left',...
        'backgroundcolor','white',...
        'String','[]');
    
    
end